[project]
name = "apriori"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apyori>=1.1.2",
    "matplotlib>=3.10.7",
    "mlxtend>=0.23.4",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
